apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: meow-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: \"false\"
spec:
  rules:
  - http:
      paths:
      - path: /meow/
        backend:
          serviceName: meow-svc
          servicePort: 80
      - path: /meow2/
        backend:
          serviceName: meow-svc-2
          servicePort: 80
