apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: api-test-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: \"false\"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: api-test-svc
          servicePort: 8080
