apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongod
  labels:
    app: mongod
spec:
  serviceName: mongo
  replicas: 3
  selector:
    matchLabels:
      app: mongod
  template:
    metadata:
      labels:
        app: mongod
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongod
        image: mongo
        command:
          - mongod
          - "--replSet"
          - "MainRepSet"
          - "--bind_ip"
          - 0.0.0.0
        #resources:
        #  requests:
        #    cpu: 0.2
        #    memory: 200Mi
        ports:
        - containerPort: 27017
          name: mongo
        volumeMounts:
          - name: mongo-persistent-storage
            mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongo-persistent-storage
      annotations:
        volume.beta.kubernetes.io/storage-class: "standard"
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
